ribbon:
  IsSecure: false
pivotal:
  quotesService:
    name: quotes-service
  userService:
    name: user-service  
  accountsService:
    name: accounts-service
  portfolioService:
    name: portfolio-service
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN
